- name: Deploy Node.js App via Systemd
  hosts: all
  become: yes
  tasks:
    - name: Download Node.js setup script
      get_url:
        url: https://deb.nodesource.com/setup_24.x
        dest: /tmp/nodesource_setup.sh
        mode: '0755'

    - name: Run Node.js setup script
      shell: /tmp/nodesource_setup.sh

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Create app directory
      file:
        path: /home/laborant/myapp
        state: directory
        owner: laborant
        group: laborant
        mode: '0755'

    - name: Copy Application Files
      copy:
        src: "{{ item }}"
        dest: /home/laborant/myapp/
        owner: laborant
        group: laborant
      with_items:
        - "../index.js"
        - "../package.json"

    - name: Install dependencies
      npm:
        path: /home/laborant/myapp

    - name: Copy Service file
      copy:
        src: "../myapp.service"
        dest: /etc/systemd/system/myapp.service

    - name: Reload Systemd
      systemd:
        daemon_reload: yes

    - name: Start and Enable Service
      systemd:
        name: myapp
        state: restarted
        enabled: yes